#
# DNS upstream torproject.org
#
forward-zone:
    name: "onion"
    forward-tls-upstream: yes
    forward-addr: 127.0.0.1@9053    # Redirect to Tor DNS


#
# DNS upstream Cloudflare
#
forward-zone:
	name: "."				    # use for ALL queries
	forward-tls-upstream: yes	# use DNS-over-TLS forwarder
	forward-first: no			# do NOT send direct
	forward-addr: 1.1.1.1@853	# Cloudflare DNS-over-TLS
