authoritative;

# speedport.ip
subnet 192.168.0.0 netmask 255.255.255.0 {
    range 192.168.0.200 192.168.0.220;
    option broadcast-address 192.168.0.255;
    option subnet-mask 255.255.255.0;
    option routers 192.168.0.1;
    option domain-name-servers 192.168.0.1;
    option domain-name "speedport.ip"
}

# lan.local
subnet 192.168.1.0 netmask 255.255.255.0 {
    range 192.168.1.2 192.168.1.3;
    option broadcast-address 192.168.1.255;
    option subnet-mask 255.255.255.0;
    option routers 192.168.1.1;
    option ntp-servers 192.168.1.1;
    option domain-name-servers 192.168.1.1;
    option domain-name "lan.local"

    host z620 {
        hardware ethernet 88:51:fb:3f:2c:e4;
        fixed-address 192.168.1.20;
        server-name "z620.lan.local";
    }
    host z600 {
        hardware ethernet 2c:27:d7:35:97:bc;
        fixed-address 192.168.1.50;
        server-name "z600.lan.local";
    }
}


