#	$OpenBSD: ldapd.conf,v 1.1 2014/07/11 21:20:10 deraadt Exp $

schema  "/etc/ldap/core.schema"
schema  "/etc/ldap/inetorgperson.schema"
schema  "/etc/ldap/nis.schema"
schema  "/etc/ldap/bsd.schema"

listen on "/var/run/ldapi"
listen on lo0

Namespace "dc=lan,dc=local" {
  rootdn  "cn=admin,dc=lan,dc=local"
  rootpw  "changeme"
  index   sn
  index   givenName
  index   cn
  index   mail
}
