# $OpenBSD: ntpd.conf,v 1.16 20260321 wandsas Exp $
#
# See ntpd.conf(5) and /etc/examples/ntpd.conf

# Listen for clients
listen on 2001:db8:acab::1

# Pools
servers pool.ntp.org
server time.cloudflare.com
sensor *

constraint from "9.9.9.9"              # quad9 v4 without DNS
constraint from "2620:fe::fe"          # quad9 v6 without DNS
constraints from "www.google.com"      # intentionally not 8.8.8.8
