# $OpenBSD: pf.conf,v 1.55 20260320 wandsas Exp $
#
# See pf.conf(5) and /etc/examples/pf.conf

ext_if = "cad0"
int_if = "axen0"

icmp_types = "{ echoreq unreach }"
icmp6_types = "{ echoreq unreach timex paramprob routeradv routersol neighbradv neighbrsol }"

# Non-routable and reserved address space
table <martians> { 0.0.0.0/8 10.0.0.0/8 127.0.0.0/8 169.254.0.0/16 \
	127.16.0.0/12 192.0.0.0/24 192.0.2.0/24 224.0.0.0/3 \
	192.168.0.0/16 198.18.0.0/15 198.51.100.0/24 203.0.113.0/24 }

# Defaults
set block-policy drop
set loginterface egress
set skip on lo

# Normalize traffic
match in all scrub (no-df random-id max-mss 1440)

# NAT for lan.local to current egress address.
match out on egress inet from $int_if:network to any nat-to (egress:0)
match out on egress inet6 from $int_if:network to any nat-to (egress:0)

# Anti-spoofing
antispoof quick for { egress, $int_if }
block in quick on egress from <martians> to any
block out quick on egress from any to <martians>

# Default deny
#block all	# block stateless traffic

# Router solicitation
pass inet proto icmp keep state
pass inet6 proto icmp6 keep state

# Permit LAN
pass in on egress inet proto { tcp udp } from $int_if:network to any keep state
pass in on egress inet6 proto { tcp udp } from $int_if:network to any keep state

# Outbound WAN
# Allow established and related traffic
pass out on egress inet from any to any keep state
pass out on egress inet6 from any to any keep state

# DNS
pass in on egress inet proto { tcp udp } from any to $int_if:network port domain
pass in on egress inet proto { tcp udp } from any to $int_if:network port domain-s
pass in on egress inet6 proto { tcp udp } from any to $int_if:network port domain
pass in on egress inet6 proto { tcp udp } from any to $int_if:network port domain-s

# Redirect dns querries to unbound.
#pass in on $int_if proto { tcp udp } from any to any port domain rdr-to 127.0.0.1 port domain

# By default, do not permit remote connections to X11
#block return in on ! lo0 proto tcp to port 6000:6010
