# $OpenBSD: pf.conf - minimal router/firewall with NAT for a LAN 2026/02/05 Exp $
#
# See pf.conf(5) and /etc/examples/pf.conf
ext_if = "smsc0"
int_if = "axen0"
lan_net = "192.168.1.0/24"

icmp_types = "{ echoreq unreach }"
icmp6_types = "{ echoreq unreach timex paramprob routeradv routersol neighbrsol }"

# Non-routable and reserved address space
table <martians> { 0.0.0.0/8 10.0.0.0/8 127.0.0.0/8 169.254.0.0/16 \
		172.16.0.0/12 192.0.0.0/24 192.0.2.0/24 224.0.0.0/3 \
		192.168.0.0/16 198.18.0.0/15 198.51.100.0/24 203.0.113.0/24 }

# Default settings
set block-policy drop
set loginterface egress
set skip on lo

# Normalize traffic
match in all scrub (no-df random-id max-mss 1440)

# NAT for LAN to the current egress address
match out on egress inet from $int_if:network to any nat-to (egress:0)

# Anti-spoofing
antispoof quick for { egress, $int_if }
block in quick on egress from <martians> to any
block out quick on egress from any to <martians>

# Default deny
block return	# block stateless traffic
pass		# establish keep-state

pass inet proto icmp icmp-type $icmp_types keep state
pass inet6 proto icmp6 icmp6-type $icmp_types keep state

# Allow established and related traffic
pass out on egress inet keep state
pass in on egress inet proto { tcp udp } from any to $int_if:network port domain
pass in on egress inet proto { tcp udp } from any to $int_if:network port domain-s

# Allow LAN to everywhere
pass in on egress inet proto { tcp udp } from $int_if:network to any keep state

# Redirect all dns queries
pass in on $int_if proto { tcp, udp } from any to any port domain rdr-to 127.0.0.1 port domain
