# $OpenBSD: ypldap.conf,v 1.1 2014/07/11 21:20:10 deraadt Exp $

interval	60
domain		"lan.local"
provide map	"passwd.byname"
provide map	"passwd.byuid"
provide map	"group.byname"
provide map	"group.bygid"
provide map	"netid.byname"

directory "127.0.0.1" {
  # directory options
  binddn "cn=admin,dc=lan,dc=local"
  bindcred "changeme"
  basedn "dc=lan,dc=local"
  # starting point for groups directory search, default to basedn
  groupdn "ou=Groups,dc=lan,dc=local"

  # passwd maps configuration (RFC 2307 posixAccount object class)
  passwd filter "(objectClass=posixAccount)"

  attribute name maps to "uid"
  fixed attribute passwd "*"
  attribute uid maps to "uidNumber"
  attribute gid maps to "gidNumber"
  attribute gecos maps to "cn"
  attribute home maps to "homeDirectory"
  attribute shell maps to "loginShell"
  fixed attribute class ""

  # group maps configuration (RFC 2307 posixGroup object class)
  group filter "(objectClass=posixGroup)"

  attribute groupname maps to "cn"
  fixed attribute grouppasswd "*"
  attribute groupgid maps to "gidNumber"
  # memberUid returns multiple group members
  list groupmembers maps to "memberUid"
}
