# $OpenBSD forward-zones.conf 2026/02/05 wandsas Exp $

# DNS upstream telekom
forward-zone:
    name: speedport.ip
    forward-addr: fe80::1%em0

# DNS upstream torproject.org
forward-zone:
	name: tor
	forward-tls-upstream: yes
	forward-addr: 127.0.0.1@9053

# DNS upstream cloudflare
forward-zone:
	name: .
	forward-tls-upstream: yes
	forward-first: no
	forward-addr: 1.1.1.1@853

# Use an upstream forwarder (recursive resolver) for some or all zones.
#
#forward-zone:
#	name: "."				# use for ALL queries
#	forward-addr: 192.168.1.1		# example address only
#	forward-first: yes			# try direct if forwarder fails

# Use an upstream DNS-over-TLS forwarder and do not fall back to cleartext
# if that fails.
#forward-zone:
#	name: "."
#	forward-tls-upstream: yes		# use DNS-over-TLS forwarder
#	forward-first: no			# do NOT send direct
#	# the hostname after "#" is not a comment, it is used for TLS checks:
#	forward-addr: 192.0.2.53@853#resolver.hostname.example
