# $OpenBSD: forward.conf,v 1.21 2025/03/20 wandsas Exp $

#forward-zone:
#	name: "speedport.ip"
#	forward-addr: fe80::1%cad0
#	forward-addr: 192.168.0.1

# Use TCP for "forward-zone" requests. Useful if you are making
# DNS requests over an SSH port forwarding.
#
tcp-upstream: yes

# Use an upstream forwarder (recursive resolver) for some or all zones.
#
forward-zone:
	name: "lan.local"			# use for ALL queries
	forward-addr: 1.1.1.1@853		# example address only
	forward-first: yes			# try direct if forwarder fails


# Use an upstream DNS-over-TLS forwarder and do not fall back to cleartext.
#
#forward-zone:
	#name: "."
	#forward-tls-upstream: yes		# use DNS-over-TLS forwarder
	#forward-first: no			# do NOT send direct
	# the hostname after "#" is not a comment, it is used for TLS checks:
#	forward-addr: 1.1.1.1
#@853#resolver.hostname.example
