# $OpenBSD: lan-zones.conf,v 1.21 2025/03/20 wandsas Exp $

server:
	do-not-query-localhost: no
	domain-insecure: "lan.local"
	domain-insecure: "1.0.0.in-addr-arpa"

	# Unblock reverse lookups for LAN addresses
	unblock-lan-zones: yes
	insecure-lan-zones: yes

	local-zone: lan.local nodefault
	local-zone: 1.0.0.in-addr.arpa nodefault

	local-data: "router.lan.local IN A 192.168.1.1"
	local-data-ptr: "192.168.1.1 router.lan.local"

	local-data: "z620.lan.local IN A 192.168.1.20"
	local-data-ptr: "192.168.1.20 z620.lan.local"

	local-data: "z600.lan.local IN A 192.168.1.50"
	local-data-ptr: "192.168.1.50 z600.lan.local"	
	

	# Serve zones authoritatively from Unbound to resolver clients.
	# Not for external service.
	#
	#local-zone: "local." static
	#local-data: "mycomputer.local. IN A 192.0.2.51"
	#local-zone: "2.0.192.in-addr.arpa." static
	#local-data-ptr: "192.0.2.51 mycomputer.local"


