# $OpenBSD local-zones.conf 2026/02/05 wandsas Exp $

do-not-query-localhost: no

# The insecure-lan-zones option disables validation for
# these zones, as if they were all listed as domain-insecure.
insecure-lan-zones: yes

domain-insecure: "lan.local"
domain-insecure: "1.0.0.in-addr.arpa"

private-domain: "lan.local"
private-domain: "1.0.0.in-addr.arpa"

# Serve zone authoritatively from Unbound to resolver clients.
# Not for external service.
local-zone: lan.local nodefault
local-zone: 1.0.0.in-addr.arpa nodefault
# router
local-data: "router.lan.local IN A 192.168.1.1"
local-data-ptr: "192.168.1.1 router.lan.local"
# z620
local-data: "z620.lan.local IN A 192.168.1.20"
local-data-ptr: "192.168.1.20 z620.lan.local"
# z600
local-data: "z600.lan.local IN A 192.168.1.50"
local-data-ptr: "192.168.1.50 z600.lan.local"
# ldap01.lan.local
local-data: "ldap01.lan.local IN A 192.168.1.2"
local-data-ptr: "192.168.2.2 ldap01.lan.local"
# dns01.lan.local
local-data: "dns01.lan.local IN A 192.168.1.3"
local-data-ptr: "192.168.2.3 dns01.lan.local"
# proxy01.lan.local
local-data: "proxy01.lan.local IN A 192.168.1.4"
local-data-ptr: "192.168.2.4 proxy01.lan.local"


#
# Stub-zones
#

stub-zone:
	name: "lan.local"
	stub-addr: 127.0.0.1

stub-zone:
	name: "1.0.0.in-addr.arpa"
	stub-addr: 127.0.0.1
