do-not-query-localhost: no
domain-insecure: "lan.local"
domain-insecure: "1.0.0.in-addr.arpa"

# The insecure-lan-zones option disables validation for
# these zones, as if they were all listed as domain-insecure.
insecure-lan-zones: yes

# Serve zones authoritatively from Unbound to resolver clients.
# Not for external service.
local-zone: lan.local nodefault
local-zone: 1.0.0.in-addr.arpa nodefault
local-data: "router.lan.local IN A 10.0.0.1"
local-data-ptr: "10.0.0.1 router.lan.local"
local-data: "z620.lan.local IN A 10.0.0.20"
local-data-ptr: "10.0.0.20 z620.lan.local"
local-data: "z600.lan.local IN A 10.0.0.50"
local-data-ptr: "10.0.0.50 z600.lan.local"


private-domain: "lan.local"
private-domain: "1.0.0.in-addr.arpa"

stub-zone:
    name: "lan.local"
    stub-addr: 127.0.0.1

stub-zone:
    name: "1.0.0.in-addr.arpa"
    stub-addr: 127.0.0.1
