# $OpenBSD: unbound.conf,v 1.21 2026/02/05 02:46 wandsas Exp $

server:
	port: 53

	username: _unbound
	directory: /var/unbound
	chroot: /var/unbound
	pidfile: /var/run/unbound.pid

	interface: 127.0.0.1
	interface: ::1
	interface: 192.168.2.1
	#outgoing-interface: 192.168.2.1

	access-control: 0.0.0.0/0 refuse
	access-control: 127.0.0.0/8 allow
	access-control: 192.168.2.0/24 allow
	access-control: ::0/0 refuse
	access-control: ::1 allow

	hide-identity: yes
	hide-version: yes
	qname-minimisation: yes

	# DNS ROOT-SERVERS information
	# This file hold the information on root name servers needed to
	# initialize cache of Internet domain servers
	# (e.g. reference this file in the "cache . <file>"
	# configuration file of BIND domain name servers).
	# ftp ftp://FTP.INTERNIC.NET/domain/named.cache
	root-hints: /var/unbound/etc/root.hints

	# Perform DNSSEC validation.
	auto-trust-anchor-file: "/var/unbound/db/root.key"
	val-log-level: 2

	# Synthesize NXDOMAINs from DNSSEC NSEC chains.
	# https://tools.ietf.org/html/rfc8198
	#
	aggressive-nsec: yes

	# Serve zones authoritatively from Unbound to resolver clients.
	# Not for external service.
	#
	#local-zone: "local." static
	#local-data: "mycomputer.local. IN A 192.0.2.51"
	#local-zone: "2.0.192.in-addr.arpa." static
	#local-data-ptr: "192.0.2.51 mycomputer.local"

	# Use TCP for "forward-zone" requests. Useful if you are making
	# DNS requests over an SSH port forwarding.
	#
	#tcp-upstream: yes

	# CA Certificates used for forward-tls-upstream (RFC7858) hostname
	# verification.  Since it's outside the chroot it is only loaded at
	# startup and thus cannot be changed via a reload.
	tls-cert-bundle: "/etc/ssl/cert.pem"

include: /var/unbound/etc/local-zones.conf
include: /var/unbound/etc/forward-zones.conf
include: /var/unbound/etc/conf.d/*.conf

remote-control:
	control-enable: yes
	control-interface: /var/run/unbound.sock
